name: TweetNaCl Tests and Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main-test:
    name: Main Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run all tests
      run: yarn test
  
  test-nacl:
    name: Test nacl.js
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run tests for nacl.js
      run: NACL_SRC=nacl.js yarn test-node
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: nacl-test-results
        path: |
          test/browser/_bundle.js
          test/browser/_bundle-quick.js

  test-nacl-fast:
    name: Test nacl-fast.min.js
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run tests for nacl-fast.min.js
      run: NACL_SRC=nacl-fast.min.js yarn test-node

  benchmark-nacl:
    name: Benchmark nacl.js
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run benchmarks for nacl.js
      run: NACL_SRC=nacl.js yarn bench | tee bench_nacl_results.txt
    
    - name: Upload nacl.js benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: nacl-benchmark-results
        path: bench_nacl_results.txt
    
    - name: Post benchmark results
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const benchResults = fs.readFileSync('bench_nacl_results.txt', 'utf8');
          
          const comment = `## Benchmark Results for nacl.js
          
          \`\`\`
          ${benchResults}
          \`\`\`
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  benchmark-nacl-fast:
    name: Benchmark nacl-fast.min.js
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run benchmarks for nacl-fast.min.js
      run: NACL_SRC=nacl-fast.min.js yarn bench | tee bench_nacl_fast_results.txt
    
    - name: Upload nacl-fast.min.js benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: nacl-fast-benchmark-results
        path: bench_nacl_fast_results.txt
    
    - name: Post benchmark results
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const benchResults = fs.readFileSync('bench_nacl_fast_results.txt', 'utf8');
          
          const comment = `## Benchmark Results for nacl-fast.min.js
          
          \`\`\`
          ${benchResults}
          \`\`\`
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          }); 